# Generated by Django 5.0 on 2023-12-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washmachine',
            name='mode',
            field=models.CharField(max_length=101),
        ),
    ]
