// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi2.Data;

namespace webapi2.Migrations
{
    [DbContext(typeof(DbContextShape))]
    partial class DbContextShapeModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("webapi.model.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CountOfAngle")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Perimetr")
                        .HasColumnType("float");

                    b.Property<int?>("ShapeCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShapeCategoryId");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("webapi.model.ShapeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShapeCategory");
                });

            modelBuilder.Entity("webapi.model.Shape", b =>
                {
                    b.HasOne("webapi.model.ShapeCategory", "ShapeCategory")
                        .WithMany("Shapes")
                        .HasForeignKey("ShapeCategoryId");

                    b.Navigation("ShapeCategory");
                });

            modelBuilder.Entity("webapi.model.ShapeCategory", b =>
                {
                    b.Navigation("Shapes");
                });
#pragma warning restore 612, 618
        }
    }
}
